### ISSUE TITLE
Remove easyb module and all references to it

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#277]
Originally created by Marcin Erdmann.

I don't think anyone is using it. There's no point in supporting it.

**Comment by dbh** [comment]
My group at work uses EazyB and is interested in using GEB. 
What would be involved in getting EazyB added back into GEB? What would be necessary to support it?

**Comment by erdi** [comment]
I'm personally not interested in bringing the support back. It was broken for ages and nobody complained hence I decided to remove it because it made me believe that nobody is using it.

What you could do is to craft some support based on things that were removed in this commit: https://github.com/geb/geb/commit/b71ad448e26ba8af3b5ad4c4b866e71ce04ba8c1

**Comment by dbh** [comment]
Were there issues known in the Eazyb module other than those listed by searching for issues with "is:issue easyb"?

**Comment by erdi** [comment]
No, there were no issues reported other than tests for that module have not been run for a long time and when I tried to run them everything failed.
