### ISSUE TITLE
PhantomJS reporting an unexpected error

### ISSUE THREAD

**Issue by glnds** [geb/issues#394]
The following code (baseurl is used):

    class PixxisHomePage extends Page {
        static at = { title.equals("Pixxis") }
        static content = {
            menu { module MenuModule }
        }
    }

Runs fine under Chrome and FireFox but fiails under PhantomJS
Assertion failed: 
title.equals("Pixxis")
|     |
""    false
	at PixxisHomePage._clinit__closure1(PixxisHomePage.groovy:8)
	at PixxisHomePage._clinit__closure1(PixxisHomePage.groovy)

The full project is availabel here:
https://github.com/glnds/GebSpockExample

**Comment by erdi** [comment]
Your issue is too generic to be considered to be honest. 

Please start a discussion on [user mailing list](http://www.gebish.org/lists) with more details and we can take it from there. Given that it works for you in regular browsers I'm inclined to say that it might be an issue in the PhantomJS driver over which Geb has no control.
