### ISSUE TITLE
support angularjs test

### ISSUE THREAD

**Issue by gqlxj1987** [geb/issues#413]
from geb, we know it support Javascript, AJAX and dynamic pages. Right row, most website use angularjs to build, to support angularjs, geb have some plan?

Thanks

**Comment by erdi** [comment]
What kind of support are you expecting?

**Comment by gqlxj1987** [comment]
for example, angularjs use $scope to do everything, geb can test some attr in $socpe?

**Comment by erdi** [comment]
Yes, assuming that you included jquery in your angular app then you can easily access an attribute in a  scope of an element using the following (this is Geb/Groovy code, not javascript code):

    $("div.ng-scope").jquery.scope().someScopeValue

I'm closing this issue because it's generic and we don't plan to add any specific support for angular to be honest. If you have questions with regards to testing angular apps with Geb then please ask them on the [user mailing list](https://groups.google.com/d/forum/geb-user).
