### ISSUE TITLE
Appium and Perfecto Support

### ISSUE THREAD

**Issue by TheJusticeLeague** [geb/issues#443]
I think it is possible to implement support for Appium (Native-App Testing) using Appium Driver that extends WebDriver. Also I think it is possible to test using Perfecto Mobile via Appium (Testing on a cloud provider of real devices).

I think this can be done by creating a new DriverFactory (e.g. PerfectoDriverFactory) that can afterwards be used via a plugin. The User name and password are not as in sauce labs in the url, but instead passed as a capability.  With the support for Appium we can also add new capabilities such as deviceName, deviceOrientation, etc...

I would be willing to make this change :-)

**Comment by erdi** [comment]
Hi @TheJusticeLeague,

First of all thanks for your contribution offer and asking before committing any time into implementing anything.

Integrations with BrowserStack and SauceLabs have been added as Gradle plugins to Geb modules because Geb uses these tools internally in its test harness. This means that there is in-house knowledge needed to maintain them and maintenance cost is relatively low.

When it comes to Appium and Perfecto it's a different story - we won't be using it internally and we lack skills and time to maintain it. I think that it makes more sense for you to release it as a separate module and we will advertise it through The Book of Geb. What do you think about such approach?

**Comment by TheJusticeLeague** [comment]
Hello :-),

That sounds like a plan! I will make the separate module and inform in this thread once I am done!

Thank you! :-)

**Comment by erdi** [comment]
Thanks,

I will close this issue for now.
