### ISSUE TITLE
Save frames along with parent HTML

### ISSUE THREAD

**Issue by prabhjot-bb** [geb/issues#448]
Currently, the page reporter only saves the parent HTML without frames. As is the saved HTML is not of much use when parent has only frames. Request to enhance the PageSourceReporter to save frames as well.

**Comment by erdi** [comment]
I agree but this should be an opt-in extension in a form of a `FramesSourceReporter` and not a change to `PageSourceReporter` because it will need to find all frames on the page by executing a WebDriver command which will carry a performance penalty for people whose tests are not dealing with sites using frames.

**Comment by ghost** [comment]
[frame_test1.txt](https://github.com/geb/issues/files/1457822/frame_test1.txt)
I have tried to address this issue via https://github.com/geb/geb/pull/131 without creating a new FramesSourceReporter. Sample output attached.
