### ISSUE TITLE
Add support for Screenplay pattern

### ISSUE THREAD

**Issue by gijsleussink** [geb/issues#455]
I read this article about Screenplay pattern, according to the authors a possible successor to the PageObject pattern:
https://ideas.riverglide.com/page-objects-refactored-12ec3541990

What do you find of it?

To get inspired, the implementation of the pattern in Serenity-BDD is hosted here:
https://github.com/serenity-bdd/serenity-core/tree/master/serenity-screenplay
https://github.com/serenity-bdd/serenity-core/tree/master/serenity-screenplay-webdriver
(John Ferguson Smart is one of the authors of the article and creator of Serenity-BDD)

How about adding support for the Screenplay pattern in Geb? Would that be useful / creating value for the tests that Geb is part of? (To decide or do a spike, do we perhaps need examples?)

I think that Geb has a significant advantage because it's using Groovy. So the readability of a test, written in a Screenplay way can be very good. What are called Targets and is quite some code in Serenity-BDD-Screenplay, are content-elements in PageObjects in Geb, for example.

```
public class ToDoList {
  public static Target WHAT_NEEDS_TO_BE_DONE = the(“’What needs to be done?’ field”).locatedBy(“#new-todo”);
  public static Target ITEMS = the(“List of todo items”).locatedBy(“.view label”);
}
```

I'm curious as to what the creators of Geb think about this.

**Comment by erdi** [comment]
Thanks for starting a conversation about this, @gijsleussink.

After having a second look at the article introducing the screenplay pattern in Serenity (first time being when you tweeted it) I'm now quite certain that implementing the screenplay pattern in itself is out of scope of Geb.

Geb is not a testing framework (that's because it comes with integrations with testing frameworks like Spock, JUnit, TestNG or Cucumber) and it feels that Serenity is a testing framework and the screenplay pattern is an acceptance testing pattern. Because Geb is in essence about making it easier to use WebDriver and there is a Serenity integration with WebDriver (which you linked to) it should be possible to write a Serenity integration with Geb.

What worries me a bit is that from looking at the sheer number of classes in the `serenity-screenplay-webdriver` module providing such integration seems to be a mammoth task. One way of going about it would be to take one of our example projects, e.g. https://github.com/geb/geb-example-gradle, trying to rewrite it using serenity without using `serenity-screenplay-webdriver` and seeing how it looks and what would potentially be worth lifting from it into a potential integration. Would you be up for doing that @gijsleussink? I'd be very happy to review and discuss the next steps, if any.

**Comment by erdi** [comment]
Btw, there also seems to be Serentity integration for Spock (https://github.com/serenity-bdd/serenity-core/tree/master/serenity-spock). It looks a little bit dead but it's definitely resurrectable.

**Comment by erdi** [comment]
Closing the issue because we came to an agreement with @gijsleussink in a conversation via a different channel that implementing the screenplay pattern in itself is out of scope of Geb.
