### ISSUE TITLE
Interact block not working : java.lang.IllegalArgumentException: Key Down / Up events only make sense for modifier keys

### ISSUE THREAD

**Issue by GodwinTerence1** [geb/issues#457]
Interact block not working . Tried the below method and returned the below error

interact {
            keyDown(Keys.F5)            
            keyUp(Keys.F5)            
        }

java.lang.IllegalArgumentException: Key Down / Up events only make sense for modifier keys

**Comment by erdi** [comment]
This is not an issue with Geb and the exception from WebDriver that you are getting explains clearly what the problem is - you should only use `keyDown()` and `keyUp()` with modifier keys like `SHIFT`, `CONTROL`, `ALT`.

If you want to send an `F5` key press then use [`Actions.sendKeys()`](http://static.javadoc.io/org.seleniumhq.selenium/selenium-api/2.53.1/org/openqa/selenium/interactions/Actions.html#sendKeys-java.lang.CharSequence...-)
