### ISSUE TITLE
Feature: Safe Navigator Object Access

### ISSUE THREAD

**Issue by rsgross** [geb/issues#458]
Occasionally while running geb tests, a test will crash with the selenium webdriver throwing a StaleElementReferenceException. The cause of this is explained in the following blog post: http://darrellgrainger.blogspot.com/2012/06/staleelementexception.html. 

In summary, this occasionally happens because the DOM is updated between the time that a page element is grabbed and it is interacted with. What makes this bug particularly annoying is that it does not happen consistently since it takes just the right timing for this to happen. To fix this I propose overloading all element access methods with single parameter methods. These parameters with specify a number of tries to conduct before an error is thrown; not unlike the simple solution that is proposed in the blog post. It is important to implement because a StaleElementReferenceException causes geb tests to crash which can be misleading in a QA environment.

**Comment by erdi** [comment]
There already is a retry mechanism in Geb in the form of [`waitFor() method`] (http://www.gebish.org/manual/current/#waiting). It's specifically designed to deal with page content that changes dynamically like in your case. Is there a reason why you can't use it?

**Comment by rsgross** [comment]
I thought that the waitFor method was meant to encapsulate a block that should evaluate to a boolean value. It is possible to imagine a scenario where the waitFor method does not have a boolean expression. Or is there another use case for the waitFor method that I am missing?

**Comment by erdi** [comment]
That is partially true, it is meant to encapsulate a block that returns a
"truthy" (see http://groovy-lang.org/semantics.html#Groovy-Truth) value and
return that value. What is not documented, and we should probably create an
issue for changing it, is that waitFor retries not only when the provided
block evaluates to a falsey value but also when it throws an exception.
Because non empty Navigator instances evaluate to true (Navigator provides
a customisation to it's Groovy Truth as per the link I pasted above) the
following:

```waitFor { $("#some-element") }```

will only return a Navigator if the selector returns a non empty Navigator
and not throw any exceptions while evaluating it. It will otherwise retry
up to the point of the default waiting timeout expiring and throw an
exception.
