### ISSUE TITLE
1.1 started to encode query parameter value

### ISSUE THREAD

**Issue by jochenberger** [geb/issues#466]
After upgrading from 1.0 to 1.1, one of my tests started to fail.
I use `to PageClass, key: value`. 1.0 did not URL-encode value but 1.1 does.
Probably caused by #463 (https://github.com/geb/geb/commit/d48ffc7d97e6e8f719d641c2d4eceb7f352d498c).

**Comment by erdi** [comment]
Is there any other reason apart from this being a breaking change for you to file this issue? You would clearly want your query parameters to be encoded as per spec, wouldn't you?

**Comment by jochenberger** [comment]
No, I don't want them encoded, I do that myself. My servlet uses a custom URL encoding pattern and IMO Geb should not mandate one.

**Comment by erdi** [comment]
Sorry, I don't understand what you mean by "custom URL encoding". Can you please give an example of a raw value and then the value encoded by you and by Geb where the two are different? As far as I can tell there is only one valid (i.e. obbeying the standard) URL encoding. I'm not trying to be dismissive, I'm just trying to better understand the issue.

**Comment by jochenberger** [comment]
Sure:
```
Input: {
Encoded by Geb: %7B
Encoded by Apache Tapestry: $007b
```
Because of that, I encode the parameter with Tapestry's URLEncoder in my test. Geb 1.0 left it alone but Geb 1.1 encodes it again.
Actually, in my test, the parmeter value is a JSON object:
```
input: {foo: "bar"}
after I encode it: $007bfoo:$0020$0022bar$0022$007d
after Geb encodes that: %24007bfoo%3A%240020%240022bar%240022%24007d
```

**Comment by erdi** [comment]
Thanks for providing the example, @jochenberger.

Just to be clear, according to https://en.wikipedia.org/wiki/Query_string#URL_encoding and https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters a valid URL should not contain a `$` in a query param value. So whatever Tapestry is doing it is not obeying the RFC for URLs.

Anyhow, I recognise that this is a breaking change and you should be able to get your values into query string without encoding if you are dealing with already escaped values to avoid double encoding.

I would like to keep encoding by default though. Would introducing a `UrlFragment.escaped(Map<?, ?> fragmentMap)` similar to [`UrlFragment.of(Map<?, ?> fragmentMap)`](https://github.com/geb/geb/blob/d48ffc7d97e6e8f719d641c2d4eceb7f352d498c/module/geb-core/src/main/groovy/geb/url/UrlFragment.groovy#L47) but without escaping keys and values that can then be used with `to()` like this: `to PageClass, UrlFragment.escaped(key: value)` work for you?

**Comment by jochenberger** [comment]
That'll probably work.
On a side note, I wonder why the encoded string shows up inside my servlet code at all. Shouldn't it have been decoded by the servlet *container* already?

**Comment by erdi** [comment]
Awesome, will add this and release as 1.1.1.

I do not know if it should be decoded or not - I'm not proficient with Servlet API. A quick google seems to suggests that `ServletRequest.getParameterMap()` returns them raw and it's up to the caller to decode them.

**Comment by jochenberger** [comment]
I'm not too familiar with the topic myself. I'm actually not sure if Geb should encode the values at all. Isn't that up to the browser?

**Comment by jochenberger** [comment]
I'm still trying to trace, where the call to `to PageClass, key: value` will go through. Does it go through `Browser.toQueryString`? Sorry if I'm being bothersome, but I've got the impression that there's an encoding step happening that shouldn't happen.

**Comment by erdi** [comment]
You're not bothersome at all, we are just trying to track the place where things go wrong.

I don't think that it's up to the browser to encode the url, you should always give the properly encoded url as there might be instances where browser won't be able to know if it should encode something or not (why would we need encoding in the first place if it was not necessary?). I know that some browsers will try to be nice and encode the url for you if they are able to given that are able to figure out what needs to be encoded.

I'm having another look at it and it seems that the query values have always been escaped by Geb [here](https://github.com/geb/geb/blob/4b0e1913002b513b9247d3ac6a128d271d58a0e2/module/geb-core/src/main/groovy/geb/Browser.groovy#L938) - this line of code has not changed since 2014. So it looks like things might be actually double encoded if you are seeing changes in the behaviour of your tests. It's possible that it's double encoded [here](https://github.com/geb/geb/blob/4b0e1913002b513b9247d3ac6a128d271d58a0e2/module/geb-core/src/main/groovy/geb/Browser.groovy#L967). Leave it with me. Whatever the problem is it will be solved with a 1.1.1 release.

Thanks for reporting and bearing with me.

**Comment by jochenberger** [comment]
That's what I meant when I asked about `Browser.toQueryString`. ;-) Thanks for your help!

**Comment by erdi** [comment]
Superseded by #469.
