### ISSUE TITLE
Book of Geb Gradle example has 2x unused variables

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [geb/issues#468]
The code example at http://www.gebish.org/manual/current/#gradle has two unused variables:

```
def gebVersion = "1.1"
def seleniumVersion = "2.52.0"
```

**Comment by BillyRayPreachersSon** [comment]
They're still showing on the website in the code example at http://www.gebish.org/manual/current/#gradle.

The only thing that seems to have changed is the `gebVersion` variable being bumped from `1.1` to `1.1.1`.

**Comment by erdi** [comment]
The fix will only show up in the snapshot version (after the build passes but it doesn't at the moment because the change broke a somewhat unrelated test which needs fixing) or in docs for a new release. Current stable docs don't change after they have been released to enable seeing docs for older versions.

**Comment by erdi** [comment]
The fix has now been published to the site in the latest snapshot version of the documentation: http://www.gebish.org/manual/snapshot/#gradle.
