### ISSUE TITLE
GStrings in attribute selectors do not work

### ISSUE THREAD

**Issue by robaca** [geb/issues#525]
It should be possible to pass GStrings for attribute values. 

The following content definition does not resolve:
```
accountLink { id -> $('a', href: "/account/$id/profile") }
```
but the following does:
```
accountLink { id -> $('a', href: "/account/$id/profile" as String) }
```
It took me an hour to find the problem, as I just did expect id had to work.

**Comment by erdi** [comment]
Can you please confirm which version of Geb you are seeing this with,
Carsten?

**Comment by robaca** [comment]
@erdi I tried with geb-spock 2.0 and 2.1 (groovy 2.4.10)

**Comment by erdi** [comment]
So you tried with the latest, cool. I’ll take a look.

**Comment by erdi** [comment]
Thanks for reporting, this indeed was a bug.

The issue was more obscure than simply selection for `GString` attributes not working at all. Translation between attribute maps and css selectors indeed did not work for `GString` attributes which meant that it fell back to filtering in the JVM by retrieving attributes and then checking that against the provided value. In general filtering still worked but with somehow downgraded performance if you used `GString` attributes. It did not work anymore if the value returned for an attribute was different when retrieved using WebDriver commands from what was being matched using css selectors. The `href` attribute is one example because when retrieved using WebDriver the protocol and hostname are prepended to its value but protocol and hostname are not required when matching using a css attribute selector. So you were somewhat unlucky to encounter the issue but on the other hand thanks to that happening it has been discovered and is now fixed.
