### ISSUE TITLE
Add range input module

### ISSUE THREAD

**Issue by mkutz** [geb/issues#551]
Geb should have a module for range inputs. See [specification in HTML 5.2](https://www.w3.org/TR/2017/REC-html52-20171214/sec-forms.html#range-state-typerange) or [documentation at W3Schools](https://www.w3schools.com/tags/att_input_type_range.asp).

**Comment by mkutz** [comment]
The range input is very similar to the number input. It might be a worth creating a `NumberLikeInput`. Opinions?

**Comment by erdi** [comment]
Yeah, I agree. As far as I can tell it will be pretty much the same from Geb's point of view other than the different input type name.

**Comment by mkutz** [comment]
I again had to implement the tests as real browser tests. It seems that HtmlUnit is generally bad at supporting fancy input types. We should keep an eye on these tests.

Maybe it is also worth thinking about a different test setup, that does not require Sauce Labs or similar external services. In my [geb-testing-workshop](https://github.com/mkutz/geb-testing-workshop) I'm using Docker on Travis to fire up a local Selenium container. Maybe that's an idea to improve local development on Geb itself.

**Comment by erdi** [comment]
The thing is that SauceLabs is there because Geb is tested with a wider matrix of browsers (including IE and Safari) than what is available in a docker container. So SauceLabs and BrowserStack setup is there to stay and I don't feel like adding another mechanism to do the same thing but locally especially given the small set of tests that are annotated with `@RequiresRealBrowser`. I appreciate that it's a bit painful to work on the ones that are but on the other hand having a different setup for CI and local will most likely lead to the local setup rotting and not working anymore because of how little it will be used.

**Comment by erdi** [comment]
Thinking about it a bit more, we could probably replace the tasks running against chrome and FF on Linux in SauceLabs/BrowserStack to run locally. We already have [these browsers installed in the docker image used on CI](https://github.com/geb/ci-docker-image/blob/master/Dockerfile#L14) anyway. Would you care to create an issue for this?

**Comment by mkutz** [comment]
Done. See #555. Feel free to edit.
