### ISSUE TITLE
GEB website should support HTTPS

### ISSUE THREAD

**Issue by lacasseio** [geb/issues#588]
Browsing to https://www.gebish.org gives a `NET::ERR_CERT_COMMON_NAME_INVALID`. I would expect the certificate to be valid.

**Comment by erdi** [comment]
Thanks for pointing it out. Back in the day getting a certificate was very expensive so that's why it wasn't done. 

The site is hosted on heroku so unfortunately I was not able to simply use letsencrypt certs on the free tier and had to upgrade to hobby dynos but I can live with the expense.

I've also added redirects from www.gebish.org to gebish.org and from http to https.
