### ISSUE TITLE
Update to Groovy 3+ and Spock 2.0+ respectively

### ISSUE THREAD

**Issue by sporkisfaster** [geb/issues#619]
Groovy 3 and Spock 2.0 have been around for some time. It would be nice to allow the upgrade to those dependencies and take advantage of their new features and fall in line with current standards.

**Comment by erdi** [comment]
Thanks for this suggestion, @sporkisfaster. Please not that while Groovy 3.0 has indeed been released in February, Spock 2.0 final has not been yet released - milestone 3 has been released in June. 

I'm currently working on Geb 4.0. When that is out of the door and Spock 2.0 final is released we can take a look at actioning this request. Given that bumping major version of Groovy will not be backwards compatible I'm going to set the target for this to be Geb 5.0.

**Comment by kriegaex** [comment]
I would kindly ask you to reconsider and upgrade to Spock 2 (i.e. introduce a Spock 2 module/adapter) now:
  * The same day Spock 1.3 was published in February, the first 2.0 milestone was published, see the [list of Spock releases](https://github.com/spockframework/spock/releases).
  * There will be no more bug fixes, feature backports or anything else for Spock 1.x. Instead, the ongoing line of development is 2.x.
  * Each single milestone release is stable, i.e. the tests existing in 1.3 plus many new ones pass, old bugs have been fixed, new features introduced. Spock 2.0-Mx are stable releases.
  * A milestone is not like a release candidate. The Maven project does the same with several plugins such as Surefire/Failsafe: They have a roadmap for a "final" release, but the milestones are official releases which can be used in production.

It would be nice and also make sense if Spock 2.0 and Geb 4.0 would be in sync.

**Comment by erdi** [comment]
Thanks for sharing your thoughts on this. The release train for Geb 4.0 is currently in motion and I would rather not add another module to it. I'm also reluctant to introduce `geb-spock2` as a separate module because I would like to switch to Spock 2.x as "the" version going forward and not "a" version.

Given that [users have reported Geb working with Spock 2.0](https://github.com/geb/issues/issues/539#issuecomment-742777999) you might as well just try it yourself if you have a hard requirement to use that version. Geb is currently not tested with Spock 2.0 as part of the core repo so using the two together is not officially supported which on the other hand does not mean that they cannot be used together.

There currently aren't any major stories in the backlog so switching to Groovy 3.x and Spock 2.x even if it is still in the milestone stage might happen sooner rather than later. On the other hand I currently do not have the capacity to officially support more than one major version of Groovy and Spock with Geb.

**Comment by Vampire** [comment]
> Given that bumping major version of Groovy will not be backwards compatible I'm going to set the target for this to be Geb 5.0.

This could be split actually.
Spock 2 supports Groovy 2.5 and Groovy 3.0.
So you can also update to Spock 2 with Groovy 2.5 and in a separate step to Groovy 3.0 if you like. :-)

**Comment by erdi** [comment]
For those interested, 5.0-SNAPSHOT which is built with Groovy 3.0.7 and Spock 2.0-M5-groovy-3.0 is now available from [https://gebish.org/manual/current/#snapshot-repository](Sonatype's OSS Snapshot repo). I will release a milestone in the coming weeks as long as nobody reports any major issues so if you can take it for a spin then it would be appreciated. I will release a 5.0 final after Spock 2.0 final is released.

**Comment by darxriggs** [comment]
Spock 2.0 has been released on 2021-05-17 (https://spockframework.org/spock/docs/2.0/release_notes.html).

Looking forward to the Geb 5.0 release.

**Comment by kriegaex** [comment]
May I ask why you upgraded to M5, even though 2.0 final was released a while ago? Is there any incompatibility?

**Comment by erdi** [comment]
It's on final, it was only M5 in a milestone published prior to final being published. See https://github.com/geb/geb/commit/b56f9552bcd90cfae38054fca95e15c08777c06b.

**Comment by kriegaex** [comment]
Oh OK, the commit you had linked to before, still had M5. I didn't check the whole commit history, just followed the link.

**Comment by erdi** [comment]
Yeah, it only got linked now because I merged 5.x branch which contained it into master today. The linked commit itself is actually quite old, like almost 5 months old. I forgot to also add a reference to this issue to the commit on which I bumped the dependency from M5 to final hence your confusion. Sorry about that.
