### ISSUE TITLE
Extend GebTestManager to allow for complex driver usecases

### ISSUE THREAD

**Issue by leonard84** [geb/issues#630]
We are using the `GebConfig` mechanism to run tests either locally via `firefox`/`chrome`, remotely via `saucelabs`, or in docker via `TestContainers`.

Since we use `TestContainers` conditionally we can't rely on its framework support to properly close the docker. So we had to add this bit of hacky code.

```groovy

    @Shared
    BrowserWebDriverContainer testcontainer

    @Override
    Browser createBrowser() {
        def browser_ = super.createBrowser()
        def container = browser_.config.rawConfig['container']
        if (container) {
            testcontainer = container() as BrowserWebDriverContainer
            testcontainer.start()
            browser_.driver = testcontainer.webDriver
        }
        return browser_
    }

    @Override
    void resetBrowser() {
        // we need to save a reference to the driver before we reset the browser
        def driver = browser.driver
        super.resetBrowser()
        // Close the driver to create a new SauceLabs Test Instance
        if (saucelabsDriver) {
            driver.quit()
        }
        testcontainer?.stop()
    }

    static boolean isSaucelabsDriver() {
        System.getProperty('geb.env')?.contains('saucelabs')
    }
```

The new `GebTestManager` adds support for a custom `Supplier<Browser> browserCreator`, but there is no way to properly hook into the `resetBrowser` method, 

Furthermore, we need access to the `BrowserWebDriverContainer` to properly shut it down. A possible solution would be to add some sort of `context` support to the `Browser` so that we could store the reference to the container there.

Full config (removed some internal stuff, .txt as github does not allow .groovy upload).
[GebConfig.groovy](https://github.com/geb/issues/files/5868707/GebConfig.txt)

**Comment by erdi** [comment]
Thanks for providing a detailed explanation of your use case and patience waiting for me to get back to you.

While we could open `GebTestManager` up and provide a hook around `resetBrowser()` your use case where the `WebDriver` instance is not supposed to be cached and have `quit()` called on it every time the `Browser` instance is reset feels common enough to be supported out of the box by Geb without the need to write any custom code by the user.

My idea is to introduce `quitDriverWhenResettingBrowser` configuration option. It would be `false` by default for backwards compatibility reasons but we could make it default to the opposite of whatever the value for `cacheDriver` is from 5.0 onwards. If you add the following class:

```
class TestcontainersWebDriver {

    private final BrowserWebDriverContainer container
    
    TestcontainersWebDriver(BrowserWebDriverContainer container) {
        this.container = container
        container.start()
    }

    //note that this will make `TestcontainersWebDriver` implement all interfaces implemented by `RemoteWebDriver`
    @Delegate 
    RemoteWebDriver getDriver() {
        container.driver
    }
    
    @Override
    void quit() {
        driver.quit()
        container.stop()
    }
}
```
then will then not need to use a custom `browserCreator` nor will you need a hook for `resetBrowser()`. All you will need will be some tweaks to your configuration:
```
...
dockerChrome { 
    driver = {
        def container = createContainer(chromeLocalCapabilities())
        new TestcontainersWebDriver(container)
    }
}
dockerFirefox {
    driver = {
        def container = createContainer(firefoxLocalOptions())
        new TestcontainersWebDriver(container)
    }
}
...
saucelabs {
    ...
    cacheDriver = false
    quitDriverWhenResettingBrowser = true
    ...
}
...
```

I will work on adding the `quitDriverWhenResettingBrowser` configuration option and when I have it implemented I will create a standalone, proof of concept project based on a snapshot version of Geb which will use the proposed mechanism to setup video recording using a Testcontainers backed browser on a per test basis to ensure that the proposed solution holds water.

**Comment by erdi** [comment]
Sorry for the delay on this but I have finally created an [example project](https://github.com/geb/geb-testcontainers-videos-per-test) showing how to setup capturing of recording for each test via Testcontainers when using the new `quitDriverOnBrowserReset` config option. I have also implemented a solution [on a branch](https://github.com/geb/geb-testcontainers-videos-per-test/tree/only-restart-vnc-container) which in my opinion is better - manually managing the vnc recording container in a Spock extension which is faster because it only restarts the vnc recording container and does not restart the browser container for each of the tests.

Please let me know your thoughts, @leonard84. I believe that with these two options your use case is covered.

**Comment by leonard84** [comment]
@kiview WDYT about adding support in Testcontainers to restart the VNC recording container, without restarting the browser container?

**Comment by leonard84** [comment]
As for the [branch](https://github.com/geb/geb-testcontainers-videos-per-test/tree/only-restart-vnc-container), I'd include a `browser.go("about:blank")` before the `vncContainer.start()` to better isolate the videos, once https://github.com/geb/issues/issues/634 is fixed, otherwise it would need to be `browser.driver.get("about:blank")`.

If it should be turned into a full featured extension, the recording should support the same `@Stepwise` logic as the browser.
Also, the recording mode is currently ignored (ALL or only failed), and the file naming is different.

IMHO, it would be a good thing if geb offers direct support for Testcontainer Browsers, instead of users having to use this as template.
Whether the video recording restarting would be done in the extension or implemented in Testcontainers needs to be decided as well.

**Comment by erdi** [comment]
So, after a bit more pondering on this, I think that with #632 your team will no longer be blocked on upgrading to 4.x and will not be worse off than it is at the moment because you are currently recreating a Testcontainers backed driver instance after each test anyway. So I would like to release 4.1, close this issue and then improve support for recording a separate video per test using `BrowserWebDriverContainer` as a separate step. This would involve a couple of things:
1. Firstly open an issue with https://github.com/testcontainers/testcontainers-java to ask whether @kiview, @rnorth and @bsideup would be happy to accept a PR with a mode added to `BrowserWebDriverContainer` which would restart the `VncRecordingContainer` each time `org.testcontainers.containers.BrowserWebDriverContainer.retainRecordingIfNeeded()` is called. I really don't want to get involved in working around this limitation of `BrowserWebDriverContainer` in Geb - it will make things harder for me than they should be, only Geb's users could benefit from that and finally it's not Geb's responsibility to be working around it. Therefore I believe it's essential to fix this upstream.
1. If we get a go-ahead then I will work on a PR, if not then that's the end of the road, as far as I'm concerned.
1. Open an issue with Geb to add some sugar which would allow to easily reuse a single, cached instance of `BrowserWebDriverContainer` provided driver for all of the tests yet get separate recordings separate for each of the tests.

How does that sound, @leonard84?

**Comment by leonard84** [comment]
Sounds good to me
