### ISSUE TITLE
`setBaseUrl()` breaking parallel execution 

### ISSUE THREAD

**Issue by robaca** [geb/issues#680]
In the past, we had a test setup with Spock 1.3 and Geb 3.3, with parallel execution of tests, launching tests in parallel via the JUnit Runner API, which was working flawlessly.

Now while migrating to Spock 2.3 and Geb 6, calling the junit platform API in parallel threads, we run into an issue with `setBaseUrl()`. 

We are testing multiple sites (tenants) in parallel. If one test is calling `setBaseUrl` during `setupSpec()` to change into the domain of that tenant, this affects other parallel tests executions, even when these are using different drivers (`cacheDriverPerThread = true`).

**Comment by robaca** [comment]
On further investigation, I see that the browser.config is at least ThreadLocal. As we use a thread pool, can it be that the config is not fully reset between subsequent test launches? 

I will try to workaround this by explicitly setting a default baseUrl in our spec base class.

**Comment by robaca** [comment]
The workaround is solving the issue for us.

**Comment by erdi** [comment]
The change in behaviour is due to https://github.com/geb/issues/issues/660 which is indeed a breaking change in 6.0. I'm glad that you found a workaround for this already but there is another workaround if you already have a base class - you can bring back the old behaviour with this code:
```
class CustomisedGebReportingSpec extends GebReportingSpec {

    private final static GebTestManager TEST_MANAGER = new SpockGebTestManagerBuilder()
            .withBrowserCreator { new Browser() }
            .withReportingEnabled(true)
            .build()

    @Override
    GebTestManager getTestManager() {
        TEST_MANAGER
    }
}
```
It's not nice that you have to extend the base class just to do that so I created an issue to make this easier/cleaner: https://github.com/geb/issues/issues/681. 

Apart form that, it looks like you might not be the only one depending on the old behaviour so it feels like it should be made easy to opt out of this configuration caching mechanism: https://github.com/geb/issues/issues/682.
